### ISSUE TITLE
Getting "an error occurred" on Brave and Firefox

### ISSUE THREAD

**Issue by robbie-hunt** [tomasruud/downcloud#11]
Using up to date Brave and Firefox. I sign in to Soundcloud successfully and give access to downcloud.ruud.ninja, afterwards I am simply met with "An error occurred", with your links to Github and Soundcloud below.

**Comment by robbie-hunt** [comment]
<img width="519" alt="Screenshot 2022-02-17 at 15 41 58" src="https://user-images.githubusercontent.com/69302142/154516785-b78fbca2-ae95-4bde-8500-fc4323771403.png">

**Comment by tomasruud** [comment]
Thanks for letting me know @robbie-hunt! I have been lazy and have not updated the API-integration I think, which is why this is happening. It is actually related to #10, I have just never gotten around to fix it as there are some technical difficulties regarding "download all" functionality. I will close this issue, and keep details related to this in #10.
