### ISSUE TITLE
Doesn't fetch all tracks

### ISSUE THREAD

**Issue by FatCatCoder** [tomasruud/downcloud#7]
I have over a few hundred tracks on my page but only a fraction of that shows up for download.

**Comment by tomasruud** [comment]
If you open developer tools in your browser, are you able to copy output from the console log if it contains any errors?

**Comment by FatCatCoder** [comment]
There are no errors logged but some warnings for two extensions.

**Comment by tomasruud** [comment]
That's weird. What browser are you using? Do you know exactly how many tracks you have posted on your account?

**Comment by FatCatCoder** [comment]
Chrome version 83.0.4103.116
I have 522 tracks on soundcloud.
Your program shows on the user json that I have 522 tracks too, it just doesn't have the downloads for them all.

**Comment by arnilearns** [comment]
Have same issue. I have almost 9000 tracks, that I would like to mass download. This only lists and downloads the first 90-ish tracks. Would greatly appreciate help.

**Comment by arnilearns** [comment]
Also, the files are downloaded with weird names, like "recording on Tuesday afternoon". How will I be able to identify each files when there is like 300 files with the same name and just a list number, rather than my Soundcloud file names? 

Any help is greatly appreciated!

**Comment by tomasruud** [comment]
@FatCatCoder or @arnilearns would any of you like to send me the json output of your "raw track data" so I can test using that? 

There might be an issue loading all that data, but if that's the case, I will probably see it in the raw json data. Don't post it directly here because it contains access tokens to download tracks, but you can send it to me on email using `downcloud@ruud.ninja`. I haven't really taken into consideration people having this many tracks, so it would be good to see what the actual data looks like and do some tests with it.

> Also, the files are downloaded with weird names, like "recording on Tuesday afternoon". How will I be able to identify each files when there is like 300 files with the same name and just a list number, rather than my Soundcloud file names?
> 
> Any help is greatly appreciated!

I think the file names are based on what the original file was named when uploading it to Soundcloud. Downcloud unfortunately doesn't do anything with the files or file names before downloading. So if multiple tracks were uploaded with the same file name they will probably end up with the same file name after downloading. I can see that this is unfortunate, but I'm not sure if it is possible to solve this without creating a separate backend service to handle downloads. I might look into that at some point, but it is not currently a priority as it requires more setup and maintenance costs.

**Comment by tomasruud** [comment]
@FatCatCoder This issue should hopefully be taken care of now. Please let me know if it's still a problem.
